### ISSUE TITLE
Migrating from existing API

### ISSUE THREAD

**Issue by PatricCampbell** [mplis/ama#1]
If I already have a RESTful API, what's the best way to go about transitioning it to GraphQL? Are there any good resources for doing this?

**Comment by mikeplis** [comment]
Hey Patric, thanks for the question!

I actually think the best thing to do when getting started is to set up a GraphQL API that fetches data from your existing REST API. The second half of [this](https://youtu.be/UBGzsb2UkeY) video (when he starts the node example) shows an example of how to do that, though the whole video is definitely worth watching. There's also an accompanying [blog post](http://graphql.org/blog/rest-api-graphql-wrapper/) to that video if you'd prefer that.

It's not the ideal production setup for performance reasons, since your GraphQL API will still be making several requests to your REST API, but it does allow you to spin up a GraphQL API with your existing data without having to touch your REST API at all.

Then, if you like the experience it gives you on the client side, you can start transitioning your resolvers to fetch the data directly instead calling your REST API.
